---
volumes:
  immich-data: {}
  immich-db: {}
  immich-cache: {}
  model-cache: {}

networks:
  caddy:
    external: true

services:
  immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: unless-stopped
    environment:
      TZ: Australia/Melbourne
      IMMICH_CONFIG_FILE: /immich.json
    networks:
      - default
      - caddy
    volumes:
      - immich-data:/usr/src/app/upload
      - ./immich.json:/immich.json:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/mafro/syncthing/KidsPhotos:/photos/kids
    depends_on:
      - database
      - redis
      - immich-ml
    labels:
      caddy: photos.mafro.net
      caddy.tls.ca: https://ca.mafro.net:4433/acme/acme/directory
      caddy.tls.ca_root: /root/step_ca.crt
      caddy.reverse_proxy: "{{upstreams 2283}}"

  immich-ml:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    restart: unless-stopped
    volumes:
      - model-cache:/cache

  redis:
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    restart: unless-stopped
    volumes:
      - immich-cache:/data

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - immich-db:/var/lib/postgresql/data
